import { Space_Grotesk, Inter } from "next/font/google";

import "./globals.css";
import Footer from "@/components/Footer";
import Navbar from "@/components/Navbar";
import { AuthProvider } from "./context/AuthContext";
import { UIProvider } from "./context/UIContext";

const spaceGrotesk = Space_Grotesk({
  subsets: ['latin'],
  variable: '--font-heading',
})

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-body',
})

export const metadata = {
  title: 'InkWell',
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${spaceGrotesk.variable} ${inter.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col flex-1">
        <AuthProvider>
          <UIProvider>
      <Navbar/>
      <div className=" flex-1">
        {children}
      </div>
        <Footer/>
        </UIProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
